name: Template Cleanup
on:
  push:
    branches:
      - main
    # Only run on first push to the main branch

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.event.repository.name != 'Temporal-Flow'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Remove template-specific files
        run: |
          rm -f CNAME
          # Replace the deploy.yml with a fixed version that works better for new repos
          cat > .github/workflows/deploy.yml << 'EOL'
name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `main` branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v3

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
EOL
          
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Remove template-specific files" || echo "No changes to commit"
          git push
        
      # Self-destruct this workflow after it runs once
      - name: Remove cleanup workflow
        run: |
          rm -f .github/workflows/template-cleanup.yml
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Remove cleanup workflow" || echo "No changes to commit"
          git push